[package]
name = "divamodarchive"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
diesel = { version = "2.0.0-rc.1", features = ["postgres", "extras", "r2d2"] }
dotenv = "0.15.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_with = { version = "2.0.0", features = ["chrono"] }
jsonwebtoken = "8.1.1"
lazy_static = "1.4.0"
chrono = "0.4.19"
reqwest = { version = "0.11.11", features = ["json", "multipart", "blocking"] }
toml = "0.5.9"
quick-xml = { version = "0.23.0", features = ["serialize"] }
aws-sdk-s3 = "0.16.0"
aws-config = "0.46.0"
