[package]
name = "divamodarchive"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
diesel = { version = "2.0.2", features = ["postgres", "extras", "r2d2"] }
dotenvy = "0.15.5"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_with = { version = "2.0.1", features = ["chrono"] }
jsonwebtoken = "8.1.1"
lazy_static = "1.4.0"
chrono = "0.4.22"
reqwest = { version = "0.11.12", features = ["json", "multipart", "blocking"] }
toml = "0.5.9"
quick-xml = { version = "0.25.0", features = ["serialize"] }
aws-sdk-s3 = "0.19.0"
aws-config = "0.49.0"
bigdecimal = "0.3.0"
urlencoding = "2.1.2"
