[default]
address = "0.0.0.0"
temp_dir = "storage/temp"

[default.limits]
file = "10 MiB"
"application/x-www-form-urlencoded" = "100 MiB"

[debug]
port = 8000

[release]
port = 7000
cli_colors = false
temp_dir = "storage/temp"
