[[themes]]
id = 0
url = "https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.2.1/darkly/bootstrap.min.css"
name = "Darkly"

[[themes]]
id = 1
url = "https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.2.1/zephyr/bootstrap.min.css"
name = "Zephyr"

[[themes]]
id = 2
url = "https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.2.1/quartz/bootstrap.min.css"
name = "Quartz"
