-- Your SQL goes here
CREATE TABLE reports (
	report_id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
	post_id INT NOT NULL REFERENCES posts ON DELETE CASCADE,
	description TEXT NOT NULL,
	time TIMESTAMP NOT NULL DEFAULT NOW()
);
