-- Your SQL goes here
CREATE TABLE download_stats(
	download_id SERIAL PRIMARY KEY NOT NULL,
	post_id INT REFERENCES posts ON DELETE CASCADE NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
